server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /    # 定位模板的目录
      suffix: .html  # 给返回的页面添加后缀名

mybatis:
#  mapper-locations: classpath*:mapping/*.xml
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.entity


#showSql
logging:
  level:
    com:
      example:
        mapper : debug